import {ERAS,UNITS,SKILLS,ITEMS,WEAPONS,UPGRADES,stageData} from './data.js';
import {buyUpgrade,upgradeCost,buySkill,buyItem,equipSkill,equipWeapon,buyWeaponUpgrade,weaponCost} from './shop.js';
const icon=id=>`<i data-lucide="${id}"></i>`;
export class Lobby{
  constructor({getProgress,persist,start,toast}){Object.assign(this,{getProgress,persist,start,toast});this.view='home';this.era=0;this.shopTab='upgrades';this.root=document.getElementById('lobby-content');this.nav=document.getElementById('lobby-nav');}
  open(view='home'){this.view=view;this.era=Math.floor((this.getProgress().unlocked-1)/10);this.render();}
  tabs(){const p=this.getProgress();return `<div class="era-tabs">${ERAS.map(e=>`<button data-era="${e.index}" class="${e.index===this.era?'selected':''}">${e.index>Math.floor((p.unlocked-1)/10)?icon('lock'):''}${e.name}</button>`).join('')}</div>`;}
  render(){
    const p=this.getProgress();this.nav.innerHTML=[['home','house','본부'],['campaign','map','전장'],['codex','book-open','병사 도감'],['shop','shopping-bag','상점'],['records','trophy','내 기록']].map(([id,i,name])=>`<button data-view="${id}" class="${this.view===id?'selected':''}">${icon(i)}${name}</button>`).join('');
    this.root.innerHTML=this[this.view](p);this.nav.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{this.view=b.dataset.view;this.era=Math.floor((p.unlocked-1)/10);this.render();});
    this.root.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>{this.era=Number(b.dataset.era);this.render();});
    this.root.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>this.start(Number(b.dataset.start)));
    this.root.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{this.shopTab=b.dataset.shopTab;this.render();});
    const transaction=(fn)=>{if(fn()){this.persist();this.render();}else this.toast('구매 또는 장착 조건을 확인해 주세요.');};
    this.root.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>transaction(()=>buyUpgrade(p,Number(b.dataset.upgrade))));
    this.root.querySelectorAll('[data-buy-skill]').forEach(b=>b.onclick=()=>transaction(()=>buySkill(p,b.dataset.buySkill)));
    this.root.querySelectorAll('[data-buy-item]').forEach(b=>b.onclick=()=>transaction(()=>buyItem(p,b.dataset.buyItem)));
    this.root.querySelectorAll('[data-weapon-upgrade]').forEach(b=>b.onclick=()=>transaction(()=>buyWeaponUpgrade(p,Number(b.dataset.weaponUpgrade))));
    this.root.querySelectorAll('[data-equip-weapon]').forEach(b=>b.onclick=()=>transaction(()=>equipWeapon(p,this.era,p.weapons[this.era].equipped?null:WEAPONS[this.era].id)));
    this.root.querySelectorAll('[data-skill-slot]').forEach(s=>s.onchange=()=>transaction(()=>equipSkill(p,Number(s.dataset.skillSlot),s.value)));
    window.lucide.createIcons();this.root.scrollTop=0;
  }
  soldiers(p,era){return `<div class="roster">${era.roster.map(kind=>{const u=UNITS[kind];return `<article class="soldier-card"><div class="portrait"><img src="assets-v3/${u.key}.png" alt="${u.name}"></div><div class="soldier-copy"><h3>${u.name}</h3><p>${u.role}</p><div class="stats"><div><span>체력 </span><b>${u.hp}</b></div><div><span>공격 </span><b>${Math.round(u.damage*(1+p.upgrades[2]*.05))}</b></div><div><span>피해 감소 </span><b>${Math.round(u.armor*100)}%</b></div><div><span>사거리 </span><b>${u.range}</b></div><div><span>초당 공격 </span><b>${u.rate}</b></div><div><span>생산 식량 </span><b>${u.cost}</b></div><div><span>기본 공격 </span><b>${u.damage}</b></div><div><span>이동 속도 </span><b>${u.speed}</b></div></div></div></article>`;}).join('')}</div>`;}
  loadout(p){const w=WEAPONS[this.era],state=p.weapons[this.era],locked=this.era>Math.floor((p.unlocked-1)/10);return `<div class="loadout"><section><h3>요새 장착 무기</h3><div class="weapon-row"><img src="assets-v3/${w.id}.png" alt=""><div><strong>${w.name}</strong><small>강화 ${state.level} / 5 · 공격 ${Math.round(w.damage*(1+state.level*.15))} · 사거리 ${w.range}</small><button data-equip-weapon ${locked?'disabled':''}>${icon(state.equipped?'minus':'plus')}${state.equipped?'해제':'장착'}</button></div></div></section><section><h3>출전 스킬</h3><div class="skill-slots">${p.equippedSkills.map((id,i)=>`<div class="skill-slot"><label for="loadout-${i}">슬롯 ${i+1}</label><select id="loadout-${i}" data-skill-slot="${i}">${p.ownedSkills.map(id2=>`<option value="${id2}" ${id2===id?'selected':''} ${p.equippedSkills.includes(id2)&&id2!==id?'disabled':''}>${SKILLS.find(s=>s.id===id2).name}</option>`).join('')}</select></div>`).join('')}</div><p class="muted" style="font-size:12px;margin-top:12px">보급 ${p.inventory.food} · 수리 ${p.inventory.repair} · 나팔 ${p.inventory.horn}</p></section></div>`;}
  home(p){const e=stageData(p.unlocked).era;this.era=e.index;return `<div class="camp-band"><img class="camp-bg" src="assets-v3/${e.background}.png" alt="${e.name} 전장"><div class="camp-copy"><span class="muted">현재 시대</span><h1>${e.name} 시대</h1><p class="muted">다음 전장 ${p.unlocked} / 50</p><button class="primary" data-start="${p.unlocked}">${icon('swords')}출전</button></div><div class="camp-army">${e.roster.map(k=>`<img src="assets-v3/${UNITS[k].key}.png" alt="${UNITS[k].name}">`).join('')}</div></div><div class="summary-strip"><div><small>최고 단계</small><b>${p.unlocked} / 50</b></div><div><small>클리어</small><b>${p.cleared.length}개</b></div><div><small>승리</small><b>${p.records.wins}회</b></div><div><small>처치</small><b>${p.records.kills}명</b></div></div><div class="section-heading"><h2>출전 병사</h2><span class="version-label">0.3.0</span></div>${this.soldiers(p,e)}${this.loadout(p)}`;}
  campaign(p){const e=ERAS[this.era],locked=e.index>Math.floor((p.unlocked-1)/10);return `<div class="section-heading"><h2>전장</h2><span class="muted">${p.cleared.length} / 50 클리어</span></div>${this.tabs()}<div class="stage-grid">${Array.from({length:10},(_,i)=>{const s=e.index*10+i+1,boss=stageData(s).boss;return `<button data-start="${s}" class="${boss!==null?'boss':''}" ${s>p.unlocked?'disabled':''}>${s>p.unlocked?icon('lock'):s}<small>${p.cleared.includes(s)?'클리어':boss!==null?'보스':'전투'}</small></button>`;}).join('')}</div>${locked?'<p class="locked-copy">이전 시대의 마지막 전장을 클리어하면 해금됩니다.</p>':''}${e.bosses.map(k=>`<div class="boss-preview"><img src="assets-v3/${UNITS[k].key}.png" alt="${UNITS[k].name}"><div><h3>${UNITS[k].name}</h3><p class="muted">${UNITS[k].role}</p></div></div>`).join('')}`;}
  codex(p){const e=ERAS[this.era];return `<div class="section-heading"><h2>병사 도감</h2><span class="muted">${e.name} 시대</span></div>${this.tabs()}${this.soldiers(p,e)}${this.loadout(p)}`;}
  shop(p){const available=Math.floor((p.unlocked-1)/10);let rows='';
    if(this.shopTab==='upgrades')rows=UPGRADES.map((u,i)=>`<div class="shop-row"><div class="shop-info">${icon(['wheat','castle','swords','package'][i])}<div><h3>${u.name} <small>${p.upgrades[i]} / 8</small></h3><p>${u.detail}</p></div></div><button data-upgrade="${i}" ${p.upgrades[i]>=8||p.coins<upgradeCost(p,i)?'disabled':''}>${p.upgrades[i]>=8?'최대 강화':upgradeCost(p,i)+' 금화'}</button></div>`).join('');
    if(this.shopTab==='weapons')rows=ERAS.map(e=>{const w=WEAPONS[e.index],state=p.weapons[e.index];return `<div class="shop-row"><div class="shop-info"><img src="assets-v3/${w.id}.png" alt=""><div><h3>${w.name}</h3><p>${e.name} 시대 · 강화 ${state.level} / 5<br>공격 ${Math.round(w.damage*(1+state.level*.15))} · 사거리 ${w.range}</p></div></div><button data-weapon-upgrade="${e.index}" ${e.index>available||state.level>=5||p.coins<weaponCost(p,e.index)?'disabled':''}>${e.index>available?'시대 잠김':state.level>=5?'최대 강화':weaponCost(p,e.index)+' 금화'}</button></div>`;}).join('');
    if(this.shopTab==='skills')rows=SKILLS.map(s=>`<div class="shop-row"><div class="shop-info">${icon(s.icon)}<div><h3>${s.name}</h3><p>${s.detail}<br>전리품 ${s.cost} · 재사용 ${s.cd}초</p></div></div><button data-buy-skill="${s.id}" ${p.ownedSkills.includes(s.id)||s.era>available||p.coins<s.price?'disabled':''}>${p.ownedSkills.includes(s.id)?'보유':s.era>available?ERAS[s.era].name+' 해금':s.price+' 금화'}</button></div>`).join('');
    if(this.shopTab==='items')rows=ITEMS.map(i=>`<div class="shop-row"><div class="shop-info">${icon(i.icon)}<div><h3>${i.name} <small>${p.inventory[i.id]} / 99</small></h3><p>${i.detail} · 전투당 1회</p></div></div><button data-buy-item="${i.id}" ${p.inventory[i.id]>=99||p.coins<i.price?'disabled':''}>${p.inventory[i.id]>=99?'보유 한도':i.price+' 금화'}</button></div>`).join('');
    return `<div class="section-heading"><h2>상점</h2><span class="coins">${icon('coins')}${p.coins}</span></div><div class="shop-tabs">${[['upgrades','swords','강화'],['weapons','castle','요새 무기'],['skills','sparkles','스킬'],['items','package','소모품']].map(([id,i,name])=>`<button data-shop-tab="${id}" class="${this.shopTab===id?'selected':''}">${icon(i)}${name}</button>`).join('')}</div>${rows}`;
  }
  records(p){const r=p.records;return `<div class="section-heading"><h2>내 기록</h2><span class="muted">최고 ${p.unlocked} 단계</span></div><div class="records-grid">${[['승리',r.wins],['패배',r.losses],['병사 처치',r.kills],['보스 처치',r.bossKills]].map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div>${ERAS.map(e=>`<div class="era-progress"><strong>${e.name}</strong><progress max="10" value="${p.cleared.filter(s=>Math.floor((s-1)/10)===e.index).length}"></progress><span>${p.cleared.filter(s=>Math.floor((s-1)/10)===e.index).length} / 10</span></div>`).join('')}<h3 style="margin:24px 0 12px">전장별 최단 전투 시간</h3>${Object.entries(r.bestTimes).length?Object.entries(r.bestTimes).sort((a,b)=>Number(a[0])-Number(b[0])).map(([s,t])=>`<div class="record-row"><span>${ERAS[Math.floor((s-1)/10)].name} · ${s} 전장</span><strong>${Math.floor(t/60)}분 ${Math.floor(t%60)}초</strong></div>`).join(''):'<p class="muted">아직 전투 기록이 없습니다.</p>'}`;}
}
